# Generated by Django 4.1.3 on 2022-11-30 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfconLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='EuropaLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Formula1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='NBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='NFL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Worldcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('clubimage', models.ImageField(choices=[('', ''), ('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea')], default='Manchester', max_length=220, upload_to='')),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('Afcon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Baseball', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.baseball')),
                ('Bundesliga', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.bundesliga')),
                ('Europa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.europaleague')),
                ('Formula1', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.formula1')),
                ('Laliga', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.laliga')),
                ('NBA', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nba')),
                ('NFL', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nfl')),
                ('Worldcup', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.worldcup')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
