# Generated by Django 4.1.3 on 2022-11-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_afcon_remove_profile_baseball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Afcon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Baseball',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.baseball'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bundesliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.bundesliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.europaleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Formula1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.formula1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Laliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.laliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NBA',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NFL',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nfl'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.worldcup'),
        ),
    ]
