# Generated by Django 4.1.3 on 2022-11-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_afcon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Europa',
            new_name='Europa_id',
        ),
    ]
