# Generated by Django 4.1.3 on 2022-11-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_europa_profile_europa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Europa_id',
        ),
    ]
