# Generated by Django 4.1.3 on 2022-11-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_europa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.europaleague'),
        ),
    ]
