# Generated by Django 4.1.3 on 2022-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_europa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
