# Generated by Django 4.1.3 on 2022-12-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Last_name',
            new_name='Last_Name',
        ),
    ]
