# Generated by Django 4.1.3 on 2022-12-16 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bundesliga', '0004_bundesligavideo_commentbundesligavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundesligaCommentLike1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundesligaCommentLike2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundesligaCommentLike3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesliga_comments1', to='Bundesliga.comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='Bundesligacomment_user1', through='Bundesliga.BundesligaCommentLike1', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bundesliga.comment1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesligacomments1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesliga_comments2', to='Bundesliga.comment1')),
                ('likes', models.ManyToManyField(blank=True, related_name='Bundesligacomment_user2', through='Bundesliga.BundesligaCommentLike2', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bundesliga.comment2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesligacomments2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesliga_comments3', to='Bundesliga.comment2')),
                ('likes', models.ManyToManyField(blank=True, related_name='Bundesligacomment_user3', through='Bundesliga.BundesligaCommentLike3', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bundesliga.comment3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bundesligacomments3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='bundesligacommentlike3',
            name='comment3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bundesliga.comment3'),
        ),
        migrations.AddField(
            model_name='bundesligacommentlike3',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundesligacommentlike2',
            name='comment2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bundesliga.comment2'),
        ),
        migrations.AddField(
            model_name='bundesligacommentlike2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundesligacommentlike1',
            name='comment1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bundesliga.comment1'),
        ),
        migrations.AddField(
            model_name='bundesligacommentlike1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
