# Generated by Django 4.1.3 on 2022-12-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20221009_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='countcomments',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='count_comments', to='tweets.comment'),
            preserve_default='True',
        ),
    ]
