# Generated by Django 4.1.3 on 2022-11-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0004_commentnbavideo_nbavideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
    ]
