# Generated by Django 4.1.3 on 2022-11-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0005_remove_comment_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NBA_comments', to='NBA.tweet'),
        ),
    ]
