# Generated by Django 4.1.3 on 2022-12-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0009_remove_comment_countcomments_tweet_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='countcomments',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='count_comments', to='NBA.comment'),
            preserve_default='True',
        ),
    ]
